# Generated by Django 4.0.1 on 2022-02-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='round_list',
            field=models.JSONField(default=dict),
        ),
    ]
