# Generated by Django 4.0.1 on 2022-02-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_survey_round_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='guest_can_pause',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='votes_to_skip',
        ),
    ]
