# Generated by Django 4.0.1 on 2022-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_remove_survey_guest_can_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
