# Generated by Django 4.0.1 on 2022-03-10 17:32

import audio.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_experimentee', models.BooleanField(default=True, verbose_name='experimentee status')),
                ('is_researcher', models.BooleanField(default=False, verbose_name='researcher status')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Audio_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('allow_mumble', models.BooleanField(default=False)),
                ('file_location', models.FileField(upload_to=audio.models.set_file_name)),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Audio_store',
            },
        ),
        migrations.CreateModel(
            name='AudioRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairs', models.IntegerField()),
                ('prime', models.CharField(default='X', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('j_mask', models.CharField(default='_NONE_', max_length=50)),
                ('k_mask', models.CharField(default='_NONE_', max_length=50)),
                ('public', models.BooleanField(default=False, verbose_name='public')),
                ('subscribers', models.ManyToManyField(related_name='sub', to=settings.AUTH_USER_MODEL)),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey_James',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=audio.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50)),
                ('name', models.CharField(default='Default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round_count', models.IntegerField(default=2)),
                ('round_list', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WordBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('public', models.BooleanField(default=False, verbose_name='public')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, unique=True)),
                ('audio_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audio_store')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_audio_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audioround')),
                ('audio_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audio_store')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUniqueExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField(default=0, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey_james', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.survey_james')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(max_length=100)),
                ('text', models.CharField(max_length=3000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPairGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placebo_added', models.BooleanField(default=False, verbose_name='placebo_added')),
                ('answer', models.CharField(default='NOT_ANSWERED', max_length=200)),
                ('prime', models.CharField(default='X', max_length=3)),
                ('associated_word_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.userwordround')),
                ('audio_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audio_store')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.pair')),
            ],
        ),
        migrations.CreateModel(
            name='TextRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=500)),
                ('text', models.CharField(default='text', max_length=3000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.survey')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=3000)),
                ('questionType', models.PositiveSmallIntegerField(choices=[(1, 'text'), (2, 'slider'), (3, 'yesOrNo'), (4, 'agree')], default=1)),
                ('questionNumber', models.IntegerField(max_length=100)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.survey')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('surveyQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.surveyquestion')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pair',
            name='audio1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audio1', to='audio.word'),
        ),
        migrations.AddField(
            model_name='pair',
            name='audio2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audio2', to='audio.word'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mumble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mumble', models.CharField(max_length=20, unique=True)),
                ('audio_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audio_store')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='image', max_length=300)),
                ('image', models.ImageField(upload_to=audio.models.set_image_name)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.survey')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.word')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSent', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='audioround',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment'),
        ),
        migrations.AddField(
            model_name='audioround',
            name='user_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audioround',
            name='word_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.wordbundle'),
        ),
        migrations.CreateModel(
            name='Audio_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.pair')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssociatedSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.survey')),
            ],
        ),
    ]
