# Generated by Django 4.0.1 on 2022-02-24 16:32

import audio.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpairguess',
            name='answer',
            field=models.CharField(default='NOT_ANSWERED', max_length=200),
        ),
        migrations.CreateModel(
            name='UserUniqueExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField(default=0, max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey_james', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.survey_james')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(max_length=100)),
                ('text', models.CharField(max_length=3000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=audio.models.set_image_name)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.survey')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
