# Generated by Django 4.0.1 on 2022-01-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_store',
            name='user_source',
        ),
    ]
