# Generated by Django 4.0.2 on 2022-03-04 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSent', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.experiment')),
            ],
        ),
    ]
