# Generated by Django 4.0.1 on 2022-03-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_userpairguess_answer_useruniqueexperiment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioround',
            name='mumbles',
        ),
        migrations.RemoveField(
            model_name='audioround',
            name='placebo',
        ),
        migrations.AddField(
            model_name='audioround',
            name='prime',
            field=models.CharField(default='X', max_length=3),
        ),
        migrations.AddField(
            model_name='imageround',
            name='name',
            field=models.CharField(default='image', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpairguess',
            name='prime',
            field=models.CharField(default='X', max_length=3),
        ),
    ]
