# Generated by Django 4.0.1 on 2022-01-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_remove_audio_store_user_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_store',
            name='record',
        ),
    ]
