# Generated by Django 4.0.1 on 2022-03-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_remove_audioround_mumbles_remove_audioround_placebo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textround',
            name='title',
            field=models.CharField(default='title', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageround',
            name='name',
            field=models.CharField(default='image', max_length=300),
        ),
    ]
