# Generated by Django 4.0.1 on 2022-01-31 19:33

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_alter_audio_store_file_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_store',
            name='file_location',
            field=models.FileField(default='test.wav', upload_to=audio.models.set_file_name),
        ),
    ]
